name: continuous-integration
run-name: ${{ github.actor }} is testing out the code.
on:
  push:
    branches:
    - main
  pull_request:
  workflow_call:
jobs:
  test-code:
    runs-on: ubuntu-latest
    steps:
      - name: run setup.py 
      - run:  d
